name: Deploy Laravel to Rumahweb via SSH

on:
  push:
    branches: [ main ]    # adjust if you deploy from another branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app (composer + npm)
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader
          npm ci
          npm run build
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan optimize

      - name: Deploy via SSH with rsync
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}         # e.g. serverXX.rumahweb.com
          username: ${{ secrets.SSH_USER }}     # aksj7611
          port: ${{ secrets.SSH_PORT }}         # usually 22
          key: ${{ secrets.SSH_KEY }}           # private key (paste in repo secrets)
          script_stop: true
          script: |
            # Ensure target directory exists
            mkdir -p /home/aksj7611/apps/aksaranta

      - name: Rsync files to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz --delete --exclude ".git/" --exclude ".github/" --exclude "node_modules/" --exclude "tests/" --exclude ".env"
          path: ./
          remote_path: /home/aksj7611/apps/aksaranta
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Post-deploy tasks (migrate, cache)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/aksj7611/apps/aksaranta

            # Detect Rumahweb PHP binary
            PHP_BIN=""
            for p in /opt/alt/php82/usr/bin/php /opt/alt/php81/usr/bin/php /usr/local/bin/php php; do
              if [ -x "$p" ]; then PHP_BIN="$p"; break; fi
            done
            echo "Using PHP: $PHP_BIN"

            $PHP_BIN artisan config:cache
            $PHP_BIN artisan route:cache
            $PHP_BIN artisan view:cache
            $PHP_BIN artisan migrate --force
            $PHP_BIN artisan storage:link || true
